#!/usr/bin/env sh
set -eu

protoc_bin="${PROTOC:-../server/protoc-34.1-linux-x86_64/bin/protoc}"

"$protoc_bin" \
	-I protobuf \
	--go_out=. \
	--go_opt=module=chatview \
	--go-grpc_out=. \
	--go-grpc_opt=module=chatview \
	protobuf/chatview/common/types.proto \
	protobuf/chatview/auth.proto \
	protobuf/chatview/chat.proto \
	protobuf/chatview/events.proto \
	protobuf/chatview/admin.proto
