#!/usr/bin/env sh
set -eu

tags="${GO_TAGS:-}"
if [ "${XDG_SESSION_TYPE:-}" = "wayland" ]; then
	if [ -n "$tags" ]; then
		tags="$tags,wayland"
	else
		tags="wayland"
	fi
fi

if [ -n "$tags" ]; then
	exec go run -tags "$tags" ./cmd/chatview-fyne "$@"
fi

exec go run ./cmd/chatview-fyne "$@"
